# Generated by Django 5.1.2 on 2024-10-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Architecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                (
                    "yuno_ldap",
                    models.CharField(
                        choices=[
                            ("true", "true"),
                            ("false", "false"),
                            ("not_relevant", "not_relevant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("yuno_multi_instance", models.BooleanField()),
                (
                    "yuno_sso",
                    models.CharField(
                        choices=[
                            ("true", "true"),
                            ("false", "false"),
                            ("not_relevant", "not_relevant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("yuno_high_quality", models.BooleanField()),
                ("yuno_maintained", models.BooleanField()),
                ("yuno_state", models.CharField(max_length=100)),
                ("updated", models.DateTimeField()),
                ("architectures", models.ManyToManyField(to="yuno.architecture")),
            ],
        ),
    ]
