# Generated by Django 5.1.2 on 2024-11-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yuno", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appversion",
            name="yuno_high_quality",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appversion",
            name="yuno_maintained",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
