# Generated by Django 5.1.2 on 2024-11-17 20:54

from django.db import migrations


CREATE_SQL = """
create view updates_update as
select 'upstream' as source, version, date, name, 'upstream-' || version || '-' || 'name' as id
from   git_version
join   git_gitapp on git_version.git_app_id = git_gitapp.id
union
select 'yunohost' as source, version, updated, name, 'yunohost-' || version || '-' || 'name' as id
from   yuno_appversion
"""

DROP_SQL = "drop view if exists updates_update"

class Migration(migrations.Migration):

    dependencies = [
        ("git", "0001_initial"),
        ("yuno", "0004_alter_appversion_yuno_multi_instance"),
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_SQL, reverse_sql=DROP_SQL),
    ]
