# Generated by Django 5.1.2 on 2024-11-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("updates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
