# Generated by Django 5.1.2 on 2024-11-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("remote_url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=10)),
                ("date", models.DateTimeField()),
                (
                    "git_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="git.gitapp"
                    ),
                ),
            ],
        ),
    ]
