# Generated by Django 5.1.2 on 2024-11-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0003_alter_gitapp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
