# Generated by Django 5.1.2 on 2024-11-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("git", "0004_alter_version_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitapp",
            name="manual",
            field=models.BooleanField(
                default=False, help_text="Do not update automatically"
            ),
            preserve_default=False,
        ),
    ]
