# Generated by Django 5.1.2 on 2024-11-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("git", "0005_gitapp_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitapp",
            name="manual",
            field=models.BooleanField(
                default=True, help_text="Do not update automatically"
            ),
        ),
    ]
